# Información básica del proyecto en SonarCloud
sonar.projectKey=Dorian88_ACodigoEstaticoQA
sonar.organization=innosistemas-org

# Este es el nombre del proyecto como se verá en SonarCloud
sonar.projectName=ACodigoEstaticoQA

# Directorio donde está el código a analizar
sonar.sources=src

# Directorio donde están las pruebas (esto excluye las pruebas de métricas como "deuda técnica")
sonar.tests=tests

# Archivo o directorio con el reporte de cobertura de código que generará Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# (Opcional) Especificar la codificación de los archivos fuente
sonar.sourceEncoding=UTF-8
